name: CI

on:
  push:
    branches:
      - main   # alebo tvoja hlavná branch, napr. master, main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # alebo verzia, ktorú používaš

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run tests
      run: |
        pytest tests/E2E/test_login.py -v
